//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisProgLINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class progress
    {
        public int code_stud { get; set; }
        public int code_subject { get; set; }
        public int code_lector { get; set; }
        public System.DateTime date_exam { get; set; }
        public Nullable<int> estimate { get; set; }
    
        public virtual lectors lectors { get; set; }
        public virtual students students { get; set; }
        public virtual subjects subjects { get; set; }
    }
}
