//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisProg7
{
    using System;
    using System.Collections.Generic;
    
    public partial class auto
    {
        public int id_a { get; set; }
        public string model { get; set; }
        public string num { get; set; }
        public Nullable<int> year_a { get; set; }
    
        public virtual objects objects { get; set; }
    }
}
