//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisProg7
{
    using System;
    using System.Collections.Generic;
    
    public partial class objects
    {
        public int id_o { get; set; }
        public string type_o { get; set; }
    
        public virtual auto auto { get; set; }
        public virtual users users { get; set; }
    }
}
