//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisProg7
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id_p { get; set; }
        public Nullable<int> id_s { get; set; }
        public float summa { get; set; }
        public System.DateTime pay_day { get; set; }
    
        public virtual users users { get; set; }
    }
}
